### ISSUE TITLE
Funções que utilizam muitas filas do sistema acabam ficando com parametros demais

### ISSUE THREAD

**Issue by GFiuza** [gabrielcs23/Escalonador-De-Processos#1]
O que vocês acham de criar uma estrutura de dados que armazena todas as filas? As funções de escalonamento ficam com argumentos demais...

**Comment by Vitorgus** [comment]
Pode ser. Daria pra fazer um dicionário.

**Comment by gabrielcs23** [comment]
E pq isso seria um problema? Até onde sei nem todas as funções de escalonamento usam todas as filas. Mesmo nesses casos vc passaria todas as filas mesmo assim?

**Comment by GFiuza** [comment]
Ninguém disse que isso é um problema. Só achei que poderia ser melhor pra ler o código. E você não passaria a fila, só uma estrutura que aponta onde estão as filas.

**Comment by GFiuza** [comment]
Como vai dar muito trabalho modificar o código atual por algo que não é tão importante, essa discussão vai ser fechada.
