### ISSUE TITLE
Escalonamento a longo prazo deveria liberar espaço para colocar processos de maior prioridade?

### ISSUE THREAD

**Issue by GFiuza** [gabrielcs23/Escalonador-De-Processos#2]
Estava mexendo no escalonamento a longo prazo, e pensei que seria uma boa ideia colocar o escalonador para liberar espaço quando não conseguisse inserir um processo. Por exemplo, se um processo de prioridade 1 chega ao sistema, mas não há memória disponível, o sistema deveria tentar retirar processos de prioridade 2 e 3 para que o processo de prioridade 1 pudesse ser executado mais rapidamente? Ou isso não é função do escalonamento a longo prazo, e ele deveria simplesmente ignorar?

**Comment by Vitorgus** [comment]
Caso isso acontecesse, ele não pode chamar alguma função do escalonador de médio prazo, que faz o swapping?

**Comment by GFiuza** [comment]
Mas essa é a pergunta, Vitor, ele deveria ou não fazer o swap?

**Comment by gabrielcs23** [comment]
Acho que deveria sim. Ao entrar um processo de maior prioridade ele tenta tirar alguém da mais baixa prioridade disponível. A questão é qual escalonador fica responsável pelo swap, seria o de médio chamado pelo de longo?

**Comment by GFiuza** [comment]
O swapper é o escalonador de médio prazo. Vou modificar o de longo prazo então.
