### ISSUE TITLE
Podem entrar na lista de prontos um uso maior de IO que existe

### ISSUE THREAD

**Issue by felipe-b-vieira** [gabrielcs23/Escalonador-De-Processos#3]

**Comment by felipe-b-vieira** [comment]
1, 0, 1, 1024, 0, 0, 0, 0
1, 1, 1, 1024, 0, 1, 0, 0
1, 2, 1, 1024, 0, 0, 1, 1
1, 3, 1, 1024, 0, 0, 0, 2

**Comment by GFiuza** [comment]
Um problema que eu percebi é que o escalonador a longo prazo só verifica quem tá sendo usado. Por exemplo, se chegam 2 processos ao mesmo tempo e os dois utilizam o scanner, os dois vão entrar pois o recurso de entrada e saída estão disponível para ambos, apesar de que quando forem executar, algum dos dois terá que esperar. Alguém sugere uma solução para isso?
