### ISSUE TITLE
Bug escalonador curto prazo

### ISSUE THREAD

**Issue by GFiuza** [gabrielcs23/Escalonador-De-Processos#4]
Não sei muito bem o problema, mas com a entrada:
1, 0, 3, 1024, 0, 0, 0, 0
1, 1, 4, 1024, 0, 0, 0, 0
1, 2, 5, 1024, 0, 0, 0, 0
1, 3, 2, 1024, 0, 0, 0, 0

O processo 1 e o 4 saem do sistema ao mesmo tempo (o que está errado, pois eles entram no mesmo instante e possuem tempos de execução diferentes);
No quantum = 3 o processo 3 é inserido em duas CPUs diferentes;
Ao passar para o quantum = 4 há um IndexError no método desalocaProcessosNaCPU na instrução listaExecutando.pop(cpus[i].posicaoLista) (linha 163)

**Comment by GFiuza** [comment]
Parece que o problema está na atualização do tempo restante dos processos na fila de feedback, na seguinte entrada:
1, 0, 50, 1024, 0, 0, 0, 0
1, 0, 50, 1024, 0, 0, 0, 0
1, 0, 50, 1024, 0, 0, 0, 0
1, 0, 50, 1024, 0, 0, 0, 0
Os processos deveriam ficar 50 quantum no processador, mas eles entram no quantum 1 e saem do sistema no quantum 2.

**Comment by GFiuza** [comment]
O problema parece estar também na atualização de tempo restante dos processos de usuario:
1, 1, 10, 1024, 0, 0, 0, 0
1, 2, 10, 1024, 0, 0, 0, 0
1, 3, 10, 1024, 0, 0, 0, 0
1, 1, 10, 1024, 0, 0, 0, 0

Estes processos entram no momento 1 mas saem no momento 8.

**Comment by Vitorgus** [comment]
Bug corrigido na versão mais recente
